workflows:
  android-release:
    name: Android Release
    environment:
      groups:
        - keystore # Only if you need signing (see next section)
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com # Replace with your email
