workflows:
  android-release:
    name: Android Release
    environment:
      groups:
        - keystore # Remove if not using app signing
      vars:
        ANDROID_NDK_VERSION: "21.4.7075529" # Stable NDK version
    scripts:
      - name: Set up Android SDK
        script: |
          sdkmanager --install "ndk;$ANDROID_NDK_VERSION"
          echo "ndk.dir=$ANDROID_SDK_ROOT/ndk/$ANDROID_NDK_VERSION" >> local.properties
      - flutter pub get
      - flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients: 
          - "tangihaiduwa065@gmail.com" # Must be quoted string in a list
      # slack: # Uncomment if needed
      #   channel: '#builds'
      #   notify_on_build_start: true
